version: '3'

volumes:
  data:

services:
  db:
    image: mariadb:10.3
    container_name: qodDb
    environment:
      MYSQL_ROOT_PASSWORD: REPLACE_ME
      MYSQL_PASSWORD: REPLACE_ME
      MYSQL_USER: REPLACE_ME
      MYSQL_DATABASE: REPLACE_ME
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
